language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install tox
  - pip install coveralls
  - sudo python bin/cot --force install-helpers --ignore-errors

script: tox

after_success:
  - coveralls
