language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - "pip install -r requirements.txt"
  - "sudo python setup.py install_helpers --force"
  - "python setup.py install"
script: "python setup.py test"
