language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "sudo pip install -r requirements.txt --use-mirrors"
  - "sudo python setup.py install_helpers --force"
script: "sudo python setup.py test"
