language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install tox
  - pip install coveralls
  - sudo python setup.py install_helpers --force

script: tox

after_success:
  - coveralls
